### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by joshklod** [klodnicki/crypto-tools#1]
## Primary Goals
- [x] Binance US Support
- [ ] Dollar-Cost Averaging
- [ ] Trailing Stop Orders
- [ ] Basic interface through command line or config files

## Secondary Goals
- [ ] Web/Mobile Interface with reasonable security
- [ ] User Data Privacy
- [ ] Low Balance Alerts
- [ ] Automatic Deposits
- [x] Support other Binance domains

## Probably Will Never Happen
- [ ] Multiple Users
- [x] Support Other Exchanges
